### ISSUE TITLE
acquaint - Code sharing percentage

### ISSUE THREAD

**Issue by jzeferino** [xamarinhq/app-acquaint#12]
Can you tell me how what tool did you used to measure the percentage of code sharing?

**Comment by jsauvexamarin** [comment]
There's an "Analysis" folder in both the Acquaint.Native and Acquaint.XForms folders:
https://github.com/xamarinhq/app-acquaint/tree/master/Acquaint.Native/Analysis
https://github.com/xamarinhq/app-acquaint/tree/master/Acquaint.XForms/Analysis

There's a Program.cs in each that reads the lines of code to determine how many are shared and how many are unique. You can run these yourself if you like.

I may need to update my screenshots of the results since I've done more work since the last time I ran the analysis.

**Comment by jzeferino** [comment]
Thanks for sharing. I've already seen that code on jamesmontemagno MeetupManager code.
Do you have any reason to exclude the .xaml files? (`inc.EndsWith(".xaml")`). In my opinion its relevant to include them. And in android the .xml is important too.

**Comment by jsauvexamarin** [comment]
I hadn't really considered it, but I see your point. Yes, this was borrowed from another project, quite possibly originally from James.

**Comment by jzeferino** [comment]
OK, I will play with it and do some testing. Thank you.
