### ISSUE TITLE
Android Native hitting OutOfMemory Exception when Compiling

### ISSUE THREAD

**Issue by psycosyd** [xamarinhq/app-acquaint#16]
Currently you need to set the Heap to 1G in the Android Advanced Build options. I believe this needs to be modified in the Android Manifest to Heap size of large when using Xamarin Studio. Otherwise you are unable to compile the Native project.

**Comment by hardcodet** [comment]
Can repro this in VS2015 (native only, XForms fails due to other reasons).

`java.lang.OutOfMemoryError. Consider increasing the value of $(JavaMaximumHeapSize). Java ran out of memory while executing 'java.exe -jar "C:\Program Files (x86)\Android\android-sdk\build-tools\23.0.1\\lib\dx.jar" --no-strict --dex --output=obj\Debug\android\bin obj\Debug\android\bin\classes "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v6.0\mono.android.jar" obj\Debug\__library_projects__\HockeySDK.AndroidBindings\library_project_imports\bin\classes.jar "C:\Users\Philipp Sumi\AppData\Local\Xamarin\Xamarin.Android.Support.Design\23.1.1.0\embedded\classes.jar" "C:\Users\Philipp Sumi\AppData\Local\Xamarin\Xamarin.Android.Support.v4\23.1.1.0\embedded\classes.jar" "C:\Users\Philipp Sumi\AppData\Local\Xamarin\Xamarin.Android.Support.v4\23.1.1.0\embedded\libs\internal_impl-23.1.1.jar" "C:\Users\Philipp Sumi\AppData\Local\Xamarin\Xamarin.Android.Support.v7.AppCompat\23.1.1.0\embedded\classes.jar" "C:\Users\Philipp Sumi\AppData\Local\Xamarin\Xamarin.Android.Support.v7.RecyclerView\23.1.1.0\embedded\classes.jar" "C:\Users\Philipp Sumi\AppData\Local\Xamarin\Xamarin.GooglePlayServices.Base\8.4.0\embedded\classes.jar" "C:\Users\Philipp Sumi\AppData\Local\Xamarin\Xamarin.GooglePlayServices.Basement\8.4.0\embedded\classes.jar" "C:\Users\Philipp Sumi\AppData\Local\Xamarin\Xamarin.GooglePlayServices.Maps\8.4.0\embedded\classes.jar"'	Acquaint.Native.Droid`

**Comment by jsauvexamarin** [comment]
@hardcodet, I have added the 1G java heap argument to the native version on the master branch.

Can you please provide detail on your other build issues?
