### ISSUE TITLE
Scrolling list

### ISSUE THREAD

**Issue by romuloprandini** [xamarinhq/app-acquaint#17]
I have noticed a lag (items and images disappear) in the Xamarin Forms when the list is scrolled.
Is it beacuse of ReciclerView?
All my lists in Xamarin Forms will be that behavior?

Thanks

**Comment by jsauvexamarin** [comment]
I haven't seen this happening. In iOS or Android?

BTW, the master branch will be getting a big merge from the `azure-app-service` branch soon. Many many changes are coming, including some updates to lists.

**Comment by romuloprandini** [comment]
Here are both apps, the first is the native app, and the second is the XForm app.

Native
![scrolling native app](https://cloud.githubusercontent.com/assets/1606231/16930750/98486f56-4d0b-11e6-920d-94d7aa07d6b1.gif)

Xamarin Forms
![scrolling Xforms](https://cloud.githubusercontent.com/assets/1606231/16930567/e06dddb2-4d0a-11e6-8301-bf32494e0fca.gif)

**Comment by jsauvexamarin** [comment]
Awesome. Thank you for the animations.

This is way better in the `azure-app-service` branch which will be merged to `master` hopefully in the next week or two. I'm insanely busy with a few other things at the moment.

Instead of the CircleImages plugin, I replaced it with the FFImageLoading library, which seems to have much better performance. I don't think it's the RecyclerView itself that is causing performance issues, as much as it is the image-loading strategy.

You can certainly pull down the `azure-app-service` branch right now, if you like. But be aware that I've only worked mostly in the XForms version right now, not the native versions. That's why I have not merged to `master` yet. But feel free to pull it down and take a peek at it.

**Comment by jsauvexamarin** [comment]
@romuloprandini, I just realized a project was in the wrong folder in the `azure-app-service` branch. I just corrected and committed. If you already cloned that branch, pull latest again.

**Comment by rodrigobrito** [comment]
I also got problems with the form, even plucking CircleImage the ListView constantly 
shows small lockups. :|
