### ISSUE TITLE
app-acquaint-master - How to access the data on azure?

### ISSUE THREAD

**Issue by Scherady** [xamarinhq/app-acquaint#40]
Trying to learn azure services and xamarin; I downloaded app-acquaint-master and I am trying to understand how it works. I have an azure account and I would like to access acquaint data, is it possible? If yes how could I do it?

Thanks

**Comment by jsauvexamarin** [comment]
Hi @Scherady. The app comes configured out-of-the-box to point to a default Azure App Service instance that we manage. You won't be able to directly access that data. However, you may deploy your own instance of the backend portion of the app to your own Azure App Service instance. The solution file is here: https://github.com/xamarinhq/app-acquaint/tree/master/Backend

The data that the app is seeded with is here: https://github.com/xamarinhq/app-acquaint/blob/master/App/Common/Acquaint.Data/SeedData.cs

When the mobile app first contacts the backend service, if there are no records, the app pushes the seed data into the service.

**Comment by Scherady** [comment]
thank you,
I get this error when I run the solution referenced in https://github.com/xamarinhq/app-acquaint/tree/master/Backend

=====
Application Exception
System.TypeLoadException
Failure has occurred while loading a type.

Description: HTTP 500.Error processing request.
Details: Non-web exception. Exception origin (name of application or object): Acquaint.Service.
Exception stack trace:
  at Acquaint.Service.SwaggerConfig.Register () [0x00033] in /Users/brian/Documents/4. Xamarin/app-acquaint-master/Backend/app_acquaintService/App_Start/SwaggerConfig.cs:17 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in /private/tmp/source-mono-4.8.0/bockbuild-mono-4.8.0-branch/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/corlib/System.Reflection/MonoMethod.cs:305

**Comment by jsauvexamarin** [comment]
It looks like you're trying to run the backend on a Mac. You can't do that. You need to run it on a Windows machine, or run it in an Azure App Service instance (https://azure.microsoft.com/en-us/services/app-service/). You need an Azure account for that.

**Comment by jsauvexamarin** [comment]
@Scherady, the basic steps for deploying the Azure App Service are:
(at least, this is *one* of the ways to do it)

1. Create an Azure App Service instance in the Azure portal
2. Open an Azure service solution in Visual Studio (the backend solution, in this case)
3. Right-click the app service project in visual studio, select "Deploy"
4. In the dialog that is presented, login to your Azure account (if you are not already logged in).
5. You will be presented with a list of Azure App Service instances that are associated with your Azure account. Select the one you just created.
6. Follow the wizard steps in the dialog to deploy your service.
7. Update the URL in the mobile app to point to your Azure App Service instance URL.
8. Run the mobile app

**Comment by jsauvexamarin** [comment]
@Scherady, I'm just adding some more context for you:

For step 7 above, the place where you can update the service URL in code is here: https://github.com/xamarinhq/app-acquaint/blob/master/App/Common/Acquaint.Util/Settings.cs#L44

...or you can update the URL at runtime in the app in the Settings screen (the gear icon in upper right of the main app screen). When the app detects a URL update, it deletes the local database in the app and creates a new one for the data that comes from the new app service.

**Comment by Scherady** [comment]
Thank you Joe,
I am aiming at a xamarin.forms app, I am using xamarin studio on my Mac. For step 2 do I have to use absolutely Visual Studio?

**Comment by jsauvexamarin** [comment]
Yes. Azure App Service projects are not intended to run with Mono on OS X. They are intended to run with .NET on Windows.

The Xamarin app code and the Azure App Service code in this repo share some of the same C# source, but they run in different runtimes and against different frameworks (.NET and Mono).

**Comment by jsauvexamarin** [comment]
You could deploy the compiled Azure App Service code manually (without using Visual Studio), but typically people use Visual Studio for deployment (especially when developing) or by some other automated build process.

This may help you:
https://docs.microsoft.com/en-us/azure/app-service-web/web-sites-deploy

But you're still going to need to compile the Azure App Service backend solution against .NET, not Mono. Despite the fact that it _will_ compile on the Mac, it won't run on Azure if you upload it because Azure uses the .NET runtime, not Mono. The two are not completely interchangeable.

So, yes, you will need to compile in Windows, and the easiest way to do that is with Visual Studio.

**Comment by Scherady** [comment]
I have installed Visual Studio for Mac, and frankly speaking I see no big difference with xamarin studio! Does it mean I have to install Windows in a Virtual Machine and then install Visual Studio for Windows?

**Comment by jsauvexamarin** [comment]
Yes, you need to use the Windows version of Visual Studio.

Yes, Xamarin Studio and Visual Studio for Mac are basically the same thing.

No, Visual Studio for Mac will not compile the backend code against .NET. It compiles it against Mono. Mono-compiled apps cannot run in Azure because Azure uses the .NET runtime, not Mono.

The point of this sample app is not to show you how to do everything on a Mac. The point is to show how to do Xamarin Forms app development. It just happens to use an Azure backend. The backend _could_ be anything, but it's Azure. Azure requires .NET. To compile the backend project to run in Azure, you need to compile it against .NET. To do that, you need the Windows version of Visual Studio.
